tests:
  build: .
  tty: true
  stdin_open: true
  volumes:
    - ./:/code
  working_dir: /code
  command: >
           sh -c '
           composer install
           && . ./set-env.sh
           && ./vendor/bin/phpunit
           '
